import type { Metadata } from 'next';
import Link from 'next/link';
import { Header } from '@/components/layout/Header';
import { Footer } from '@/components/layout/Footer';
import { Container } from '@/components/layout/Container';

export const metadata: Metadata = {
  title: 'Methodology - InterviewProof',
  description:
    'How InterviewProof works: our evidence-based pipeline, deterministic scoring engine, and the data sources behind every diagnostic.',
};

const PIPELINE_STEPS = [
  {
    step: 1,
    title: 'Extract',
    description:
      'Parse your resume and the job description into structured data -- skills, experience, requirements, keywords, seniority signals, and more.',
    detail: 'AI-powered extraction identifies what you bring and what the role demands.',
  },
  {
    step: 2,
    title: 'Retrieve',
    description:
      'Match against a curated database of interview rubrics, scoring criteria, and recruiter playbooks using vector similarity search.',
    detail:
      'Relevant rubric chunks are retrieved based on role type, round format, and company tier.',
  },
  {
    step: 3,
    title: 'Analyze',
    description:
      'AI-powered gap analysis compares your profile against the job requirements and retrieved rubrics to identify mismatches, missing evidence, and risk areas.',
    detail:
      'The analysis produces structured output: category scores, ranked risks, coaching insights, and recruiter signals.',
  },
  {
    step: 4,
    title: 'Score',
    description:
      'A deterministic scoring engine calculates your readiness score using weighted dimensions. The AI does not generate scores -- code does.',
    detail:
      'Reproducible, auditable, and fair. Same inputs always produce the same score.',
  },
  {
    step: 5,
    title: 'Diagnose',
    description:
      'Generate a comprehensive diagnostic: risk rankings, interview questions calibrated to your gaps, a study plan, coaching tips, and recruiter-perspective insights.',
    detail:
      'Every recommendation is traced back to specific evidence gaps between your resume and the role.',
  },
];

const SCORING_DIMENSIONS = [
  {
    name: 'Hard Match',
    weight: 35,
    description:
      'How well your technical skills, tools, and qualifications align with the explicit requirements in the job description.',
  },
  {
    name: 'Evidence Depth',
    weight: 25,
    description:
      'Whether your resume provides concrete, quantified proof of your claims -- metrics, outcomes, and specific accomplishments rather than vague assertions.',
  },
  {
    name: 'Round Readiness',
    weight: 20,
    description:
      'Your preparation level for the specific interview round type -- technical, behavioral, case study, or other formats.',
  },
  {
    name: 'Clarity',
    weight: 10,
    description:
      'How effectively your resume communicates your value -- structure, conciseness, and whether a recruiter can quickly parse your fit.',
  },
  {
    name: 'Company Proxy',
    weight: 10,
    description:
      'Company-specific factors including tier difficulty, culture signals, and how your prior experience maps to their expectations.',
  },
];

export default function MethodologyPage() {
  return (
    <>
      <Header />
      <main className="min-h-screen bg-[var(--bg-primary)]">
        {/* Overview */}
        <section className="py-20 lg:py-28">
          <Container size="md">
            <div className="mx-auto max-w-3xl text-center">
              <div className="mb-6 inline-flex items-center gap-2 rounded-full border border-[var(--border-default)] bg-[var(--bg-elevated)] px-4 py-1.5 text-xs font-semibold text-[var(--accent-primary)]">
                Our Methodology
              </div>
              <h1 className="text-4xl font-bold leading-tight text-[var(--text-primary)] sm:text-5xl">
                How InterviewProof Works
              </h1>
              <p className="mx-auto mt-6 max-w-2xl text-lg leading-relaxed text-[var(--text-secondary)]">
                InterviewProof uses an evidence-based diagnostic pipeline to identify the specific
                gaps between your profile and a role&apos;s requirements. Every score is calculated
                by code, not generated by AI.
              </p>
            </div>
          </Container>
        </section>

        {/* The Pipeline */}
        <section className="bg-[var(--bg-section-alt)] py-20 lg:py-28">
          <Container size="md">
            <div className="mx-auto max-w-3xl">
              <h2 className="text-center text-3xl font-bold text-[var(--text-primary)] sm:text-4xl">
                The Pipeline
              </h2>
              <p className="mx-auto mt-4 max-w-xl text-center text-base text-[var(--text-secondary)]">
                Your resume and job description pass through five stages, each building on the last.
              </p>

              <div className="mt-12 space-y-6">
                {PIPELINE_STEPS.map((step) => (
                  <div
                    key={step.step}
                    className="rounded-xl border border-[var(--border-default)] bg-[var(--bg-card)] p-6"
                  >
                    <div className="flex items-start gap-4">
                      <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-lg bg-[var(--accent-primary)] text-base font-bold text-white">
                        {step.step}
                      </div>
                      <div className="flex-1">
                        <h3 className="text-lg font-bold text-[var(--text-primary)]">
                          {step.title}
                        </h3>
                        <p className="mt-2 text-sm leading-relaxed text-[var(--text-secondary)]">
                          {step.description}
                        </p>
                        <p className="mt-2 text-xs leading-relaxed text-[var(--text-muted)]">
                          {step.detail}
                        </p>
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </Container>
        </section>

        {/* Scoring Dimensions */}
        <section className="py-20 lg:py-28">
          <Container size="md">
            <div className="mx-auto max-w-3xl">
              <h2 className="text-center text-3xl font-bold text-[var(--text-primary)] sm:text-4xl">
                6 Scoring Dimensions
              </h2>
              <p className="mx-auto mt-4 max-w-xl text-center text-base text-[var(--text-secondary)]">
                Your readiness score is a weighted composite of five measurable dimensions, plus a
                company difficulty adjustment.
              </p>

              <div className="mt-12 grid gap-4 sm:grid-cols-2">
                {SCORING_DIMENSIONS.map((dim) => (
                  <div
                    key={dim.name}
                    className="rounded-xl border border-[var(--border-default)] bg-[var(--bg-card)] p-5"
                  >
                    <div className="flex items-center justify-between">
                      <h3 className="text-base font-bold text-[var(--text-primary)]">{dim.name}</h3>
                      <span className="rounded-full bg-[var(--accent-primary)]/10 px-3 py-1 text-sm font-bold text-[var(--accent-primary)]">
                        {dim.weight}%
                      </span>
                    </div>
                    <p className="mt-3 text-sm leading-relaxed text-[var(--text-secondary)]">
                      {dim.description}
                    </p>
                    {/* Weight bar */}
                    <div className="mt-4 h-1.5 w-full overflow-hidden rounded-full bg-[var(--bg-elevated)]">
                      <div
                        className="h-full rounded-full bg-[var(--accent-primary)]"
                        style={{ width: `${dim.weight}%` }}
                      />
                    </div>
                  </div>
                ))}

                {/* Company Difficulty Adjustment card */}
                <div className="rounded-xl border border-dashed border-[var(--border-default)] bg-[var(--bg-elevated)] p-5 sm:col-span-2">
                  <div className="flex items-center gap-3">
                    <div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-lg bg-[var(--accent-primary)]/10">
                      <svg
                        width="16"
                        height="16"
                        viewBox="0 0 24 24"
                        fill="none"
                        stroke="var(--accent-primary)"
                        strokeWidth="2"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                      >
                        <path d="M12 20V10" />
                        <path d="M18 20V4" />
                        <path d="M6 20v-4" />
                      </svg>
                    </div>
                    <div>
                      <h3 className="text-base font-bold text-[var(--text-primary)]">
                        Company Difficulty Adjustment
                      </h3>
                      <p className="mt-1 text-sm text-[var(--text-secondary)]">
                        A 1.0x to 1.5x multiplier applied based on company tier (FAANG+, Big Tech,
                        Mid-Market, etc.) that adjusts scoring thresholds to reflect the higher bar
                        at more competitive companies.
                      </p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </Container>
        </section>

        {/* The Deterministic Principle */}
        <section className="bg-[var(--bg-section-alt)] py-20 lg:py-28">
          <Container size="md">
            <div className="mx-auto max-w-3xl">
              <h2 className="text-3xl font-bold text-[var(--text-primary)] sm:text-4xl">
                The Deterministic Principle
              </h2>
              <div className="mt-8 space-y-6 text-base leading-relaxed text-[var(--text-secondary)]">
                <p>
                  Many AI tools generate scores by asking a language model to &quot;rate this
                  candidate from 1-100.&quot; That approach is inherently unreliable -- the same
                  input can produce different scores on different runs, and there is no way to audit
                  why a particular number was chosen.
                </p>
                <p>
                  InterviewProof takes a fundamentally different approach:{' '}
                  <span className="font-semibold text-[var(--text-primary)]">
                    the AI analyzes, the code scores.
                  </span>
                </p>
                <p>
                  The language model serves as the analyst -- it extracts structured data, retrieves
                  relevant rubrics, and produces a detailed gap analysis with category-level
                  assessments. But the final readiness score is calculated by a deterministic scoring
                  engine: a set of weighted formulas implemented in code.
                </p>
                <p>This ensures three critical properties:</p>
              </div>

              <div className="mt-8 grid gap-4 sm:grid-cols-3">
                <div className="rounded-xl border border-[var(--border-default)] bg-[var(--bg-card)] p-5 text-center">
                  <div className="mx-auto flex h-10 w-10 items-center justify-center rounded-lg bg-[var(--accent-primary)]/10">
                    <svg
                      width="20"
                      height="20"
                      viewBox="0 0 24 24"
                      fill="none"
                      stroke="var(--accent-primary)"
                      strokeWidth="2"
                      strokeLinecap="round"
                      strokeLinejoin="round"
                    >
                      <path d="M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                      <path d="M9 12l2 2 4-4" />
                    </svg>
                  </div>
                  <h3 className="mt-3 text-sm font-bold text-[var(--text-primary)]">
                    Reproducibility
                  </h3>
                  <p className="mt-2 text-xs text-[var(--text-secondary)]">
                    Same inputs always produce the same score. No variance between runs.
                  </p>
                </div>

                <div className="rounded-xl border border-[var(--border-default)] bg-[var(--bg-card)] p-5 text-center">
                  <div className="mx-auto flex h-10 w-10 items-center justify-center rounded-lg bg-[var(--accent-primary)]/10">
                    <svg
                      width="20"
                      height="20"
                      viewBox="0 0 24 24"
                      fill="none"
                      stroke="var(--accent-primary)"
                      strokeWidth="2"
                      strokeLinecap="round"
                      strokeLinejoin="round"
                    >
                      <path d="M2 12s3-7 10-7 10 7 10 7-3 7-10 7-10-7-10-7z" />
                      <circle cx="12" cy="12" r="3" />
                    </svg>
                  </div>
                  <h3 className="mt-3 text-sm font-bold text-[var(--text-primary)]">
                    Auditability
                  </h3>
                  <p className="mt-2 text-xs text-[var(--text-secondary)]">
                    Every score breakdown is stored and can be inspected. You can see exactly which
                    dimensions contributed what.
                  </p>
                </div>

                <div className="rounded-xl border border-[var(--border-default)] bg-[var(--bg-card)] p-5 text-center">
                  <div className="mx-auto flex h-10 w-10 items-center justify-center rounded-lg bg-[var(--accent-primary)]/10">
                    <svg
                      width="20"
                      height="20"
                      viewBox="0 0 24 24"
                      fill="none"
                      stroke="var(--accent-primary)"
                      strokeWidth="2"
                      strokeLinecap="round"
                      strokeLinejoin="round"
                    >
                      <path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z" />
                    </svg>
                  </div>
                  <h3 className="mt-3 text-sm font-bold text-[var(--text-primary)]">Fairness</h3>
                  <p className="mt-2 text-xs text-[var(--text-secondary)]">
                    No LLM mood swings or prompt sensitivity. The scoring formula treats every
                    candidate consistently.
                  </p>
                </div>
              </div>
            </div>
          </Container>
        </section>

        {/* Data Sources */}
        <section className="py-20 lg:py-28">
          <Container size="md">
            <div className="mx-auto max-w-3xl">
              <h2 className="text-3xl font-bold text-[var(--text-primary)] sm:text-4xl">
                Data Sources
              </h2>
              <div className="mt-8 space-y-6 text-base leading-relaxed text-[var(--text-secondary)]">
                <p>
                  InterviewProof&apos;s analysis is grounded in real interview data, not generic
                  advice. Our retrieval system draws from:
                </p>
              </div>

              <div className="mt-8 grid gap-4 sm:grid-cols-2">
                <div className="rounded-xl border border-[var(--border-default)] bg-[var(--bg-card)] p-5">
                  <h3 className="text-sm font-bold text-[var(--text-primary)]">
                    50+ Hiring Rubrics
                  </h3>
                  <p className="mt-2 text-xs leading-relaxed text-[var(--text-secondary)]">
                    Structured evaluation criteria used by companies across tiers, from startups to
                    FAANG+, covering technical, behavioral, and case interview formats.
                  </p>
                </div>

                <div className="rounded-xl border border-[var(--border-default)] bg-[var(--bg-card)] p-5">
                  <h3 className="text-sm font-bold text-[var(--text-primary)]">
                    Recruiter Playbooks
                  </h3>
                  <p className="mt-2 text-xs leading-relaxed text-[var(--text-secondary)]">
                    Real screening criteria and evaluation frameworks that recruiters and hiring
                    managers use to filter candidates at each stage.
                  </p>
                </div>

                <div className="rounded-xl border border-[var(--border-default)] bg-[var(--bg-card)] p-5">
                  <h3 className="text-sm font-bold text-[var(--text-primary)]">
                    Interview Question Banks
                  </h3>
                  <p className="mt-2 text-xs leading-relaxed text-[var(--text-secondary)]">
                    Role-specific question archetypes mapped to competency areas, ensuring practice
                    questions target your actual weak points.
                  </p>
                </div>

                <div className="rounded-xl border border-[var(--border-default)] bg-[var(--bg-card)] p-5">
                  <h3 className="text-sm font-bold text-[var(--text-primary)]">
                    Company Tier Intelligence
                  </h3>
                  <p className="mt-2 text-xs leading-relaxed text-[var(--text-secondary)]">
                    Difficulty calibration data that adjusts expectations based on the company&apos;s
                    hiring bar, interview style, and competitive landscape.
                  </p>
                </div>
              </div>
            </div>
          </Container>
        </section>

        {/* CTA */}
        <section className="bg-[var(--bg-section-alt)] py-20 lg:py-28">
          <Container size="md">
            <div className="mx-auto max-w-3xl text-center">
              <h2 className="text-3xl font-bold text-[var(--text-primary)] sm:text-4xl">
                See it in action
              </h2>
              <p className="mx-auto mt-4 max-w-xl text-base leading-relaxed text-[var(--text-secondary)]">
                Upload your resume and a job description to get a full diagnostic. You&apos;ll see
                every score, every risk, and every recommendation -- with full transparency into how
                each was derived.
              </p>
              <div className="mt-8">
                <Link
                  href="/new"
                  className="inline-flex items-center justify-center gap-2 rounded-full bg-gradient-to-r from-orange-400 via-pink-500 to-purple-500 px-8 py-3.5 text-base font-semibold text-white shadow-lg shadow-pink-500/25 transition-colors hover:from-orange-500 hover:via-pink-600 hover:to-purple-600"
                >
                  Start My Diagnostic
                </Link>
              </div>
            </div>
          </Container>
        </section>
      </main>
      <Footer />
    </>
  );
}
