import type { Metadata } from 'next';
import Link from 'next/link';
import { Header } from '@/components/layout/Header';
import { Footer } from '@/components/layout/Footer';
import { Container } from '@/components/layout/Container';

export const metadata: Metadata = {
  title: 'Methodology - InterviewProof',
  description:
    'How InterviewProof works: our evidence-based pipeline, deterministic scoring engine, and the data sources behind every diagnostic.',
};

const PIPELINE_STEPS = [
  {
    step: 1,
    title: 'Extract',
    description:
      'An LLM parses your resume and job description into typed schemas -- skills taxonomy, seniority signals, requirement classification, and experience mapping. This is semantic extraction, not keyword matching.',
    detail:
      'The extraction model understands context: "led a team of 8" is a leadership signal, not just a number. Every field is structured for downstream analysis.',
  },
  {
    step: 2,
    title: 'Retrieve',
    description:
      'Your extracted profile is converted into 1536-dimensional embeddings and matched against a curated knowledge base of 50+ rubrics using pgvector cosine similarity search. This is Retrieval-Augmented Generation (RAG) -- grounding AI output in domain-specific data.',
    detail:
      'Retrieval is contextual: the system selects rubric chunks based on role type, round format, and company tier -- not random sampling.',
  },
  {
    step: 3,
    title: 'Analyze',
    description:
      'The LLM performs a gap analysis grounded in the retrieved rubric context (RAG), not just its general training knowledge. It compares your profile against real hiring criteria to identify mismatches, missing evidence, and risk areas.',
    detail:
      'Output is enforced via strict JSON schema -- structured category scores, ranked risks, coaching insights, and recruiter signals. No freeform text that can drift or hallucinate.',
  },
  {
    step: 4,
    title: 'Score',
    description:
      'A deterministic scoring engine calculates your readiness score using weighted dimensions. The AI does not generate scores -- code does. This separation is an architectural decision, not an accident.',
    detail:
      'Reproducible, auditable, and fair. Same inputs always produce the same score. The scoring formula is versioned and stored alongside every result.',
  },
  {
    step: 5,
    title: 'Diagnose',
    description:
      'Generate a comprehensive diagnostic: risk rankings, interview questions calibrated to your gaps, a study plan, coaching tips, and recruiter-perspective insights.',
    detail:
      'Every recommendation traces back to specific retrieved rubric chunks and evidence gaps -- not hallucinated advice. You can see the data trail behind each insight.',
  },
];

const SCORING_DIMENSIONS = [
  {
    name: 'Hard Match',
    weight: 35,
    description:
      'How well your technical skills, tools, and qualifications align with the explicit requirements in the job description.',
  },
  {
    name: 'Evidence Depth',
    weight: 25,
    description:
      'Whether your resume provides concrete, quantified proof of your claims -- metrics, outcomes, and specific accomplishments rather than vague assertions.',
  },
  {
    name: 'Round Readiness',
    weight: 20,
    description:
      'Your preparation level for the specific interview round type -- technical, behavioral, or research/ML formats.',
  },
  {
    name: 'Clarity',
    weight: 10,
    description:
      'How effectively your resume communicates your value -- structure, conciseness, and whether a recruiter can quickly parse your fit.',
  },
  {
    name: 'Company Proxy',
    weight: 10,
    description:
      'Company-specific factors including tier difficulty, culture signals, and how your prior experience maps to their expectations.',
  },
];

export default function MethodologyPage() {
  return (
    <>
      <Header />
      <main className="min-h-screen bg-[var(--bg-primary)]">
        {/* Overview */}
        <section className="py-20 lg:py-28">
          <Container size="md">
            <div className="mx-auto max-w-3xl text-center">
              <div className="mb-6 inline-flex items-center gap-2 rounded-full border border-[var(--border-default)] bg-[var(--bg-elevated)] px-4 py-1.5 text-xs font-semibold text-[var(--accent-primary)]">
                Our Methodology
              </div>
              <h1 className="text-4xl font-bold leading-tight text-[var(--text-primary)] sm:text-5xl">
                How InterviewProof Works
              </h1>
              <p className="mx-auto mt-6 max-w-2xl text-lg leading-relaxed text-[var(--text-secondary)]">
                InterviewProof uses an evidence-based diagnostic pipeline to identify the specific
                gaps between your profile and a role&apos;s requirements. Every score is calculated
                by code, not generated by AI.
              </p>
            </div>
          </Container>
        </section>

        {/* The Pipeline */}
        <section className="bg-[var(--bg-section-alt)] py-20 lg:py-28">
          <Container size="md">
            <div className="mx-auto max-w-3xl">
              <h2 className="text-center text-3xl font-bold text-[var(--text-primary)] sm:text-4xl">
                The Pipeline
              </h2>
              <p className="mx-auto mt-4 max-w-xl text-center text-base text-[var(--text-secondary)]">
                Your resume and job description pass through five stages, each building on the last.
              </p>

              <div className="mt-12 space-y-6">
                {PIPELINE_STEPS.map((step) => (
                  <div
                    key={step.step}
                    className="rounded-xl border border-[var(--border-default)] bg-[var(--bg-card)] p-6"
                  >
                    <div className="flex items-start gap-4">
                      <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-lg bg-[var(--accent-primary)] text-base font-bold text-white">
                        {step.step}
                      </div>
                      <div className="flex-1">
                        <h3 className="text-lg font-bold text-[var(--text-primary)]">
                          {step.title}
                        </h3>
                        <p className="mt-2 text-sm leading-relaxed text-[var(--text-secondary)]">
                          {step.description}
                        </p>
                        <p className="mt-2 text-xs leading-relaxed text-[var(--text-muted)]">
                          {step.detail}
                        </p>
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </Container>
        </section>

        {/* RAG Architecture */}
        <section className="py-20 lg:py-28">
          <Container size="md">
            <div className="mx-auto max-w-3xl">
              <div className="mb-6 text-center">
                <span className="inline-flex items-center gap-2 rounded-full border border-[var(--accent-primary)]/20 bg-[var(--accent-primary)]/5 px-4 py-1.5 text-xs font-semibold text-[var(--accent-primary)]">
                  Vertical AI Architecture
                </span>
              </div>
              <h2 className="text-center text-3xl font-bold text-[var(--text-primary)] sm:text-4xl">
                Retrieval-Augmented Generation
              </h2>
              <p className="mx-auto mt-4 max-w-xl text-center text-base text-[var(--text-secondary)]">
                Most AI tools pass your resume straight to a language model and hope for the best.
                InterviewProof uses a RAG architecture -- grounding every analysis in domain-specific
                data, not generic LLM knowledge.
              </p>

              <div className="mt-12 rounded-xl border border-[var(--border-default)] bg-[var(--bg-card)] p-6 sm:p-8">
                <h3 className="text-base font-bold text-[var(--text-primary)]">How RAG works</h3>
                <p className="mt-3 text-sm leading-relaxed text-[var(--text-secondary)]">
                  Before the AI analyzes your fit, it retrieves the most relevant hiring criteria from
                  a curated knowledge base. This means the analysis is anchored to real rubrics and
                  evaluation frameworks -- not improvised from the model&apos;s training data.
                </p>

                {/* Flow diagram */}
                <div className="mt-8 flex flex-col items-center gap-3 sm:flex-row sm:gap-0">
                  {[
                    { label: 'Resume + JD', sub: 'Your inputs' },
                    { label: 'Embeddings', sub: '1536-dim vectors' },
                    { label: 'Vector Search', sub: 'pgvector cosine similarity' },
                    { label: 'Retrieved Rubrics', sub: 'Domain-specific context' },
                    { label: 'Grounded Analysis', sub: 'RAG-powered output' },
                  ].map((node, i) => (
                    <div key={node.label} className="flex items-center gap-3 sm:flex-1">
                      <div className="flex-1 rounded-lg border border-[var(--border-default)] bg-[var(--bg-elevated)] p-3 text-center">
                        <p className="text-xs font-bold text-[var(--text-primary)]">{node.label}</p>
                        <p className="mt-0.5 text-[10px] text-[var(--text-muted)]">{node.sub}</p>
                      </div>
                      {i < 4 && (
                        <svg
                          className="hidden h-4 w-4 shrink-0 text-[var(--text-muted)] sm:block"
                          viewBox="0 0 24 24"
                          fill="none"
                          stroke="currentColor"
                          strokeWidth="2"
                          strokeLinecap="round"
                          strokeLinejoin="round"
                        >
                          <path d="M5 12h14" />
                          <path d="M12 5l7 7-7 7" />
                        </svg>
                      )}
                    </div>
                  ))}
                </div>

                <div className="mt-8 rounded-lg border border-dashed border-[var(--border-default)] bg-[var(--bg-elevated)] p-4">
                  <h4 className="text-xs font-bold text-[var(--text-primary)]">
                    Why this matters for you
                  </h4>
                  <p className="mt-2 text-xs leading-relaxed text-[var(--text-secondary)]">
                    Generic AI can tell you to &quot;quantify your achievements.&quot; RAG-grounded AI
                    can tell you that for a Senior Backend Engineer role at a Series B startup, the
                    hiring rubric specifically weights system design ownership and on-call experience --
                    and your resume is missing both. The difference is actionable specificity.
                  </p>
                </div>
              </div>

              <div className="mt-6 grid gap-4 sm:grid-cols-3">
                <div className="rounded-xl border border-[var(--border-default)] bg-[var(--bg-card)] p-5 text-center">
                  <p className="text-2xl font-bold text-[var(--accent-primary)]">50+</p>
                  <p className="mt-1 text-xs font-semibold text-[var(--text-primary)]">
                    Curated Rubrics
                  </p>
                  <p className="mt-1 text-[10px] text-[var(--text-muted)]">
                    Hand-built, not scraped
                  </p>
                </div>
                <div className="rounded-xl border border-[var(--border-default)] bg-[var(--bg-card)] p-5 text-center">
                  <p className="text-2xl font-bold text-[var(--accent-primary)]">1536</p>
                  <p className="mt-1 text-xs font-semibold text-[var(--text-primary)]">
                    Embedding Dimensions
                  </p>
                  <p className="mt-1 text-[10px] text-[var(--text-muted)]">
                    High-fidelity semantic matching
                  </p>
                </div>
                <div className="rounded-xl border border-[var(--border-default)] bg-[var(--bg-card)] p-5 text-center">
                  <p className="text-2xl font-bold text-[var(--accent-primary)]">0</p>
                  <p className="mt-1 text-xs font-semibold text-[var(--text-primary)]">
                    Hallucinated Insights
                  </p>
                  <p className="mt-1 text-[10px] text-[var(--text-muted)]">
                    Every claim is evidence-backed
                  </p>
                </div>
              </div>
            </div>
          </Container>
        </section>

        {/* Scoring Dimensions */}
        <section className="bg-[var(--bg-section-alt)] py-20 lg:py-28">
          <Container size="md">
            <div className="mx-auto max-w-3xl">
              <h2 className="text-center text-3xl font-bold text-[var(--text-primary)] sm:text-4xl">
                6 Scoring Dimensions
              </h2>
              <p className="mx-auto mt-4 max-w-xl text-center text-base text-[var(--text-secondary)]">
                Your readiness score is a weighted composite of five measurable dimensions, plus a
                company difficulty adjustment.
              </p>

              <div className="mt-12 grid gap-4 sm:grid-cols-2">
                {SCORING_DIMENSIONS.map((dim) => (
                  <div
                    key={dim.name}
                    className="rounded-xl border border-[var(--border-default)] bg-[var(--bg-card)] p-5"
                  >
                    <div className="flex items-center justify-between">
                      <h3 className="text-base font-bold text-[var(--text-primary)]">{dim.name}</h3>
                      <span className="rounded-full bg-[var(--accent-primary)]/10 px-3 py-1 text-sm font-bold text-[var(--accent-primary)]">
                        {dim.weight}%
                      </span>
                    </div>
                    <p className="mt-3 text-sm leading-relaxed text-[var(--text-secondary)]">
                      {dim.description}
                    </p>
                    {/* Weight bar */}
                    <div className="mt-4 h-1.5 w-full overflow-hidden rounded-full bg-[var(--bg-elevated)]">
                      <div
                        className="h-full rounded-full bg-[var(--accent-primary)]"
                        style={{ width: `${dim.weight}%` }}
                      />
                    </div>
                  </div>
                ))}

                {/* Company Difficulty Adjustment card */}
                <div className="rounded-xl border border-dashed border-[var(--border-default)] bg-[var(--bg-elevated)] p-5 sm:col-span-2">
                  <div className="flex items-center gap-3">
                    <div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-lg bg-[var(--accent-primary)]/10">
                      <svg
                        width="16"
                        height="16"
                        viewBox="0 0 24 24"
                        fill="none"
                        stroke="var(--accent-primary)"
                        strokeWidth="2"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                      >
                        <path d="M12 20V10" />
                        <path d="M18 20V4" />
                        <path d="M6 20v-4" />
                      </svg>
                    </div>
                    <div>
                      <h3 className="text-base font-bold text-[var(--text-primary)]">
                        Company Difficulty Adjustment
                      </h3>
                      <p className="mt-1 text-sm text-[var(--text-secondary)]">
                        A 1.0x to 1.5x multiplier applied based on company tier (FAANG+, Big Tech,
                        Mid-Market, etc.) that adjusts scoring thresholds to reflect the higher bar
                        at more competitive companies.
                      </p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </Container>
        </section>

        {/* The Deterministic Principle */}
        <section className="py-20 lg:py-28">
          <Container size="md">
            <div className="mx-auto max-w-3xl">
              <h2 className="text-3xl font-bold text-[var(--text-primary)] sm:text-4xl">
                The Deterministic Principle
              </h2>
              <div className="mt-8 space-y-6 text-base leading-relaxed text-[var(--text-secondary)]">
                <p>
                  Many AI tools generate scores by asking a language model to &quot;rate this
                  candidate from 1-100.&quot; That approach is inherently unreliable -- the same
                  input can produce different scores on different runs, and there is no way to audit
                  why a particular number was chosen.
                </p>
                <p>
                  InterviewProof takes a fundamentally different approach:{' '}
                  <span className="font-semibold text-[var(--text-primary)]">
                    the AI analyzes, the code scores.
                  </span>
                </p>
                <p>
                  The language model serves as the analyst -- it extracts structured data, retrieves
                  relevant rubrics, and produces a detailed gap analysis with category-level
                  assessments. But the final readiness score is calculated by a deterministic scoring
                  engine: a set of weighted formulas implemented in code.
                </p>
                <p>This ensures three critical properties:</p>
              </div>

              <div className="mt-8 grid gap-4 sm:grid-cols-3">
                <div className="rounded-xl border border-[var(--border-default)] bg-[var(--bg-card)] p-5 text-center">
                  <div className="mx-auto flex h-10 w-10 items-center justify-center rounded-lg bg-[var(--accent-primary)]/10">
                    <svg
                      width="20"
                      height="20"
                      viewBox="0 0 24 24"
                      fill="none"
                      stroke="var(--accent-primary)"
                      strokeWidth="2"
                      strokeLinecap="round"
                      strokeLinejoin="round"
                    >
                      <path d="M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                      <path d="M9 12l2 2 4-4" />
                    </svg>
                  </div>
                  <h3 className="mt-3 text-sm font-bold text-[var(--text-primary)]">
                    Reproducibility
                  </h3>
                  <p className="mt-2 text-xs text-[var(--text-secondary)]">
                    Same inputs always produce the same score. No variance between runs.
                  </p>
                </div>

                <div className="rounded-xl border border-[var(--border-default)] bg-[var(--bg-card)] p-5 text-center">
                  <div className="mx-auto flex h-10 w-10 items-center justify-center rounded-lg bg-[var(--accent-primary)]/10">
                    <svg
                      width="20"
                      height="20"
                      viewBox="0 0 24 24"
                      fill="none"
                      stroke="var(--accent-primary)"
                      strokeWidth="2"
                      strokeLinecap="round"
                      strokeLinejoin="round"
                    >
                      <path d="M2 12s3-7 10-7 10 7 10 7-3 7-10 7-10-7-10-7z" />
                      <circle cx="12" cy="12" r="3" />
                    </svg>
                  </div>
                  <h3 className="mt-3 text-sm font-bold text-[var(--text-primary)]">
                    Auditability
                  </h3>
                  <p className="mt-2 text-xs text-[var(--text-secondary)]">
                    Every score breakdown is stored and can be inspected. You can see exactly which
                    dimensions contributed what.
                  </p>
                </div>

                <div className="rounded-xl border border-[var(--border-default)] bg-[var(--bg-card)] p-5 text-center">
                  <div className="mx-auto flex h-10 w-10 items-center justify-center rounded-lg bg-[var(--accent-primary)]/10">
                    <svg
                      width="20"
                      height="20"
                      viewBox="0 0 24 24"
                      fill="none"
                      stroke="var(--accent-primary)"
                      strokeWidth="2"
                      strokeLinecap="round"
                      strokeLinejoin="round"
                    >
                      <path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z" />
                    </svg>
                  </div>
                  <h3 className="mt-3 text-sm font-bold text-[var(--text-primary)]">Fairness</h3>
                  <p className="mt-2 text-xs text-[var(--text-secondary)]">
                    No LLM mood swings or prompt sensitivity. The scoring formula treats every
                    candidate consistently.
                  </p>
                </div>
              </div>
            </div>
          </Container>
        </section>

        {/* Data Sources */}
        <section className="bg-[var(--bg-section-alt)] py-20 lg:py-28">
          <Container size="md">
            <div className="mx-auto max-w-3xl">
              <h2 className="text-3xl font-bold text-[var(--text-primary)] sm:text-4xl">
                Data Sources
              </h2>
              <div className="mt-8 space-y-6 text-base leading-relaxed text-[var(--text-secondary)]">
                <p>
                  InterviewProof&apos;s analysis is grounded in real interview data, not generic
                  advice. Every data source below is embedded as 1536-dimensional vectors in a
                  pgvector database, enabling contextual retrieval based on your specific role type,
                  round format, and company tier.
                </p>
              </div>

              <div className="mt-8 grid gap-4 sm:grid-cols-2">
                <div className="rounded-xl border border-[var(--border-default)] bg-[var(--bg-card)] p-5">
                  <h3 className="text-sm font-bold text-[var(--text-primary)]">
                    50+ Hiring Rubrics
                  </h3>
                  <p className="mt-2 text-xs leading-relaxed text-[var(--text-secondary)]">
                    Hand-curated evaluation criteria used by companies across tiers, from startups to
                    FAANG+, covering technical, behavioral, and research/ML interview formats. Each rubric is
                    chunked and embedded for precise vector retrieval.
                  </p>
                </div>

                <div className="rounded-xl border border-[var(--border-default)] bg-[var(--bg-card)] p-5">
                  <h3 className="text-sm font-bold text-[var(--text-primary)]">
                    Recruiter Playbooks
                  </h3>
                  <p className="mt-2 text-xs leading-relaxed text-[var(--text-secondary)]">
                    Real screening criteria and evaluation frameworks that recruiters and hiring
                    managers use to filter candidates at each stage. Embedded alongside rubrics so the
                    system retrieves the right playbook for your specific interview context.
                  </p>
                </div>

                <div className="rounded-xl border border-[var(--border-default)] bg-[var(--bg-card)] p-5">
                  <h3 className="text-sm font-bold text-[var(--text-primary)]">
                    Interview Question Banks
                  </h3>
                  <p className="mt-2 text-xs leading-relaxed text-[var(--text-secondary)]">
                    Role-specific question archetypes mapped to competency areas, ensuring practice
                    questions target your actual weak points -- not generic interview prep.
                  </p>
                </div>

                <div className="rounded-xl border border-[var(--border-default)] bg-[var(--bg-card)] p-5">
                  <h3 className="text-sm font-bold text-[var(--text-primary)]">
                    Company Tier Intelligence
                  </h3>
                  <p className="mt-2 text-xs leading-relaxed text-[var(--text-secondary)]">
                    Difficulty calibration data that adjusts expectations based on the company&apos;s
                    hiring bar, interview style, and competitive landscape. Retrieval adapts
                    dynamically to company tier.
                  </p>
                </div>
              </div>
            </div>
          </Container>
        </section>

        {/* CTA */}
        <section className="py-20 lg:py-28">
          <Container size="md">
            <div className="mx-auto max-w-3xl text-center">
              <h2 className="text-3xl font-bold text-[var(--text-primary)] sm:text-4xl">
                See it in action
              </h2>
              <p className="mx-auto mt-4 max-w-xl text-base leading-relaxed text-[var(--text-secondary)]">
                Upload your resume and a job description to get a full diagnostic. You&apos;ll see
                every score, every risk, and every recommendation -- with full transparency into how
                each was derived.
              </p>
              <div className="mt-8">
                <Link
                  href="/new"
                  className="inline-flex items-center justify-center gap-2 rounded-full bg-gradient-to-r from-orange-400 via-pink-500 to-purple-500 px-8 py-3.5 text-base font-semibold text-white shadow-lg shadow-pink-500/25 transition-colors hover:from-orange-500 hover:via-pink-600 hover:to-purple-600"
                >
                  Start My Diagnostic
                </Link>
              </div>
            </div>
          </Container>
        </section>
      </main>
      <Footer />
    </>
  );
}
